repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
    args:
      # the unit here is acutally KiB (1024 bytes)
      - '--maxkb=51200'  # match github max of 50MiB
- repo: https://github.com/hukkin/mdformat
  rev: 0.7.22  # Use the ref you want to point at
  hooks:
  - id: mdformat
    name: mdformat-lint
    args: [--wrap=80, --number]
    types: [markdown]
    additional_dependencies:
      - mdformat-tables
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    args:
      - '--select=FKA1'
      - '--kwargs-max-positional-arguments=2'
      - --kwargs-ignore-function-pattern-extend
      - ^np\..*|^pytest\..*|^random\..*|^mock\.patch.*|^patch|^re\..*|^json\..*|^os\.path\..*|^warnings\..*|^math\..*|^open|^click.option|^yaml\..*|^sys\..*|\.get$|\.replace$|\.transpose$|\.reshape$|^runner\.invoke$|^dict\.fromkeys$|^binom$
    additional_dependencies:
      - flake8-force-keyword-arguments
- repo: local
  hooks:
    - id: ruff-lint
      name: ruff-lint
      entry: poetry run ruff check --config pyproject.toml --fix --force-exclude
      require_serial: true
      language: system
      types_or: [python, pyi, jupyter]
    - id: sphinx-lint
      name: sphinx-lint
      entry: poetry run sphinx-lint --enable all --disable leaked-markup --jobs 1 --max-line-length 120 -i docs/reference/api/_implementations -i docs/interoperability/maite/_implementations -i .dev/ docs
      types: [rst]
      language: system
    - id: ruff-format
      name: ruff-format
      entry: poetry run ruff format --config pyproject.toml --force-exclude
      require_serial: true
      language: system
      types_or: [python, pyi, jupyter]
    - id: pyright
      name: pyright
      require_serial: true
      language: system
      entry: poetry run pyright
      types: [file, python]
    - id: extras-yaml
      name: Update src/nrtk/utils/_extras.yml from pyproject.toml
      entry: poetry run python src/nrtk/utils/_extras.py
      language: system
      pass_filenames: false
      always_run: true
      stages: [pre-commit]
